import './globals.css'
import { Inter } from 'next/font/google'
import styles from "./page.module.css"
const inter = Inter({ subsets: ['latin'] })
import { AiOutlineGithub } from 'react-icons/ai';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head >
      <title>Video Chat</title>
      <meta name="title" content="Video Chat"/>
      <meta name="description" content="Next.js video chat with socket.io and express, my first project using next.js and socket.io"/>

      <meta property="og:type" content="website"/>
      <meta property="og:url" content="https://website/"/>
      <meta property="og:title" content="Video Chat"/>
      <meta property="og:description" content="Next.js video chat with socket.io and express, my first project using next.js and socket.io"/>
      <meta property="og:image" content="https://i.postimg.cc/br5CdKPf/chrome-capture-2023-4-21.webp"/>

      <meta property="twitter:card" content="summary_large_image"/>
      <meta property="twitter:url" content="https://website/"/>
      <meta property="twitter:title" content="Video Chat"/>
      <meta property="twitter:description" content="Next.js video chat with socket.io and express, my first project using next.js and socket.io"/>
      <meta property="twitter:image" content="https://i.postimg.cc/br5CdKPf/chrome-capture-2023-4-21.webp"/>
    </head >
      <body className={`${inter.className} ${styles.body}`}>
        {children}
        <a 
          className={styles.githubLink}
          href="https://github.com/nickLoza/video-chat-nextjs-socket" 
          target="_blank">
          <AiOutlineGithub/>
        </a>
      </body>
    </html>
  )
}
